import React from 'react';
import ComponentCreator from '@docusaurus/ComponentCreator';

export default [
  {
    path: '/docs/__docusaurus/debug',
    component: ComponentCreator('/docs/__docusaurus/debug', 'e58'),
    exact: true
  },
  {
    path: '/docs/__docusaurus/debug/config',
    component: ComponentCreator('/docs/__docusaurus/debug/config', '2ce'),
    exact: true
  },
  {
    path: '/docs/__docusaurus/debug/content',
    component: ComponentCreator('/docs/__docusaurus/debug/content', '11b'),
    exact: true
  },
  {
    path: '/docs/__docusaurus/debug/globalData',
    component: ComponentCreator('/docs/__docusaurus/debug/globalData', 'f13'),
    exact: true
  },
  {
    path: '/docs/__docusaurus/debug/metadata',
    component: ComponentCreator('/docs/__docusaurus/debug/metadata', 'bff'),
    exact: true
  },
  {
    path: '/docs/__docusaurus/debug/registry',
    component: ComponentCreator('/docs/__docusaurus/debug/registry', '830'),
    exact: true
  },
  {
    path: '/docs/__docusaurus/debug/routes',
    component: ComponentCreator('/docs/__docusaurus/debug/routes', '13e'),
    exact: true
  },
  {
    path: '/docs/search',
    component: ComponentCreator('/docs/search', '3e9'),
    exact: true
  },
  {
    path: '/docs/',
    component: ComponentCreator('/docs/', '148'),
    routes: [
      {
        path: '/docs/next',
        component: ComponentCreator('/docs/next', '138'),
        routes: [
          {
            path: '/docs/next',
            component: ComponentCreator('/docs/next', '99a'),
            routes: [
              {
                path: '/docs/next/',
                component: ComponentCreator('/docs/next/', '8b3'),
                exact: true,
                sidebar: "myAutogeneratedSidebar"
              },
              {
                path: '/docs/next/install/',
                component: ComponentCreator('/docs/next/install/', '05c'),
                exact: true,
                sidebar: "myAutogeneratedSidebar"
              },
              {
                path: '/docs/next/install/vagrant',
                component: ComponentCreator('/docs/next/install/vagrant', 'dc4'),
                exact: true,
                sidebar: "myAutogeneratedSidebar"
              },
              {
                path: '/docs/next/install/virtual-install',
                component: ComponentCreator('/docs/next/install/virtual-install', 'd8c'),
                exact: true,
                sidebar: "myAutogeneratedSidebar"
              },
              {
                path: '/docs/next/usage/',
                component: ComponentCreator('/docs/next/usage/', '849'),
                exact: true,
                sidebar: "myAutogeneratedSidebar"
              }
            ]
          }
        ]
      },
      {
        path: '/docs/',
        component: ComponentCreator('/docs/', 'bf5'),
        routes: [
          {
            path: '/docs/',
            component: ComponentCreator('/docs/', 'dc7'),
            routes: [
              {
                path: '/docs/clusters/',
                component: ComponentCreator('/docs/clusters/', 'a72'),
                exact: true,
                sidebar: "myAutogeneratedSidebar"
              },
              {
                path: '/docs/templates/',
                component: ComponentCreator('/docs/templates/', 'd60'),
                exact: true,
                sidebar: "myAutogeneratedSidebar"
              },
              {
                path: '/docs/',
                component: ComponentCreator('/docs/', '5f2'),
                exact: true,
                sidebar: "myAutogeneratedSidebar"
              }
            ]
          }
        ]
      }
    ]
  },
  {
    path: '*',
    component: ComponentCreator('*'),
  },
];
